New and Create
grazirs/rails-contacts pull request #6
Opened 2022-02-17 00:26 UTC by grazirs

- Added new content (form)
- Added new and create in the controller
![newuser](https://user-images.githubusercontent.com/62312328/154380373-b822e3b8-c33d-4e52-86fb-dedc444b6f38.png)

2022-02-18 13:51 UTC, GabrielRMuller requested changes
não esqueça dos testes! :eyes:

2022-02-18 13:51 UTC, GabrielRMuller commented on app/controllers/users_controller.rb
> +    if user.save()
um detalhe só, não precisa dos parênteses `()` aqui

2022-02-18 13:51 UTC, GabrielRMuller commented on app/controllers/users_controller.rb
> +      redirect_to user
aqui você pode redirecionar adicionando alguma mensagem para o usuário saber que a criação deu certo

2022-02-18 13:56 UTC, grazirs commented on app/controllers/users_controller.rb
> +    if user.save()
verdade kkk vou corrigir

2022-02-22 13:19 UTC, GabrielRMuller commented on spec/requests/users_spec.rb
> +      }.to change(User, :count).by(1)
:+1:

2022-02-22 13:19 UTC, GabrielRMuller commented on spec/requests/users_spec.rb
> +      expect(response).to redirect_to user_path(User.order("created_at").last)
legal! mas não teria uma opção mais simples e segura de buscar esse User? pelo nome talvez?

2022-06-21 13:12 UTC, merged